name:                hs3
version:             0.1.0.0
github:              "bouzuya/hs3"
license:             BSD3
author:              "bouzuya"
maintainer:          "m@bouzuya.net"
copyright:           "2018 bouzuya"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/bouzuya/hs3#readme>

dependencies:
- base >= 4.7 && < 5
- amazonka
- amazonka-s3

library:
  source-dirs: src

executables:
  hs3-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs3

tests:
  hs3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs3
